language: ruby
script: bundle exec rake
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
- ruby-head
- rbx-2
- jruby-19mode
- jruby-head
matrix:
  allow_failures:
  - rvm: jruby-head
  - rvm: ruby-head
  - rvm: rbx-2
before_script:
- cp spec/functional/initializer.rb.ci spec/functional/initializer.rb
env:
  global:
  - ADYEN_MERCHANT_ACCOUNT: "VanBergenORG"
  - ADYEN_API_USERNAME: "ws@Company.VanBergen"
  - ADYEN_API_PASSWORD: "7phtHzbfnzsp"
