language: ruby
cache: bundler
script: bundle exec rake
rvm:
- "jruby"
before_install:
  - bundle --version || gem install bundler
before_script:
- cp test/functional/initializer.rb.ci test/functional/initializer.rb
env:
  global:
  - ADYEN_MERCHANT_ACCOUNT: "VanBergenORG"
  - ADYEN_API_USERNAME: "ws@Company.VanBergen"
  - ADYEN_API_PASSWORD: "7phtHzbfnzsp"
sudo: false
branches:
  only:
    - master
